### PR TITLE
Feature/refactoring: Part 1

### PR DESCRIPTION
**Pull request by damattl**
First part of the refactoring project, ready to be merged into dev,
so that others can continue working

### CODE REVIEW

**Comment by SoTBurst** [comment]
Please wait for the release

**Comment by SoTBurst** [comment]
Changing the month using gestures doesn't work anymore

**Comment by SoTBurst** [comment]
You can't deactivate "Use System Language"

**Comment by SoTBurst** [comment]
You can't update Standard Categories

**Comment by damattl** [comment]
> You can't deactivate "Use System Language"

Cant't reproduce, Button _Use System Language_ can be toggled on and off, 
the app language can then be changed

**Comment by damattl** [comment]
> You can't update Standard Categories

Can't reproduce either.
When setting a standard category in the settings screen, 
the next expense / income added is using this category

**Comment by NightmindOfficial** [comment]
@SoTBurst we need to perform the merge before the release. Reason is that unstable code is in the dev branch that needs to be resolved, but cannot be edited without the refactoring changes

**Review by NightmindOfficial — APPROVED** [review]
No conflicts as of now, SoTBurst has the final decision

**Pull request merged**
