### PR TITLE
Ready for update 1.04 (7)

### PR DESCRIPTION
**Pull request by SoTBurst**

### CODE REVIEW

**Comment by NightmindOfficial** [comment]
Advise not to merge as 1.0.4+7 milestone still has 8 open issues. If we want to progress faster I would be fine with moving some of the issues to a 1.0.5+8 milestone, but not everything.

**Comment by SoTBurst** [comment]
Please check for bugs

**Review by NightmindOfficial — CHANGES_REQUESTED** [review]
Monthly repeatables still get fucked by February 29 (tested it with a monthly repeatable on 29.02.2020 and then looked at February 2021

Also after that, all the months use the 1st of the month, not the 29th

**Comment by SoTBurst** [comment]
How should they act with a monthly on the 30.? Take the last available February date?

**Comment by NightmindOfficial** [comment]
Exactly - if the repeatable references the 29th, 30th, or 31th of a month, take the latest available day of February, assuming the user wants a repeatable to the end of the month

Tbh I don't know how if this should also hold for weekly repeatables

**Comment by NightmindOfficial** [comment]
Also just found that the app version specified in pubspec.yaml is not right. Can I change this @SoTBurst or are you working on this

**Comment by SoTBurst** [comment]
Feel free to change the pubspec.yaml

**Review by NightmindOfficial — APPROVED** [review]

**Pull request merged**
