### PR TITLE
Update for the Translation Script

### PR DESCRIPTION
**Pull request by damattl**
- Does not touch the main projects code
- Might still need some testing but works good so far
- A little bit different to use now

### CODE REVIEW

**Comment by NightmindOfficial** [comment]
Can we maybe add automisation to this? E.g. by running a server-side script that automatically translates the german version of the lang file to all other languages. Maybe there is a GitHub action for this, too. 

Problems I see so far with this is that we have "Human-made" translation e.g. in the Spanish files, containing strings that have been checked by natives. I don't want to lose those translations.

**Comment by NightmindOfficial** [comment]
@damattl

**Review by NightmindOfficial — CHANGES_REQUESTED** [review]
Marking this as a request of changes to ensure we won't lose human-translated files with this update (so we actually get the chance to talk about this before merging)

**Comment by damattl** [comment]
Rebase the translation-script folder on the updated development branch

**Pull request closed without merging**
