### PR TITLE
Fixes Linum 185

### PR DESCRIPTION
**Pull request by damattl**

### CODE REVIEW

**Review by NightmindOfficial — CHANGES_REQUESTED** [review]
Checks are failing; I will fix

**Review by NightmindOfficial — CHANGES_REQUESTED** [review]
@damattl We have a cross-issue problem here - while selecting a new language now, the app restarts (duh) to the settings screen. However, this activates a PIN check if the PIN lock is activated. From the user flow perspective, this does not make any sense and is pretty annoying. Can we build a workaround?

**Comment by damattl** [comment]
> @damattl We have a cross-issue problem here - while selecting a new language now, the app restarts (duh) to the settings screen. However, this activates a PIN check if the PIN lock is activated. From the user flow perspective, this does not make any sense and is pretty annoying. Can we build a workaround?

Not sure if this was introduced by the changes. The screen rebuilds the same. The workaround might be a little tricky

**Review by NightmindOfficial — DISMISSED** [review]
Not optimal user flow wise, but runs stable without problems on my emulator. The salmon is thus in motion.

**Review by NightmindOfficial — APPROVED** [review]
The salmon is not motionless; hence, it is löpping.

**Pull request merged**
