### PR TITLE
Feature/enter screen swipe

### PR DESCRIPTION
**Pull request by TheBlueBaronx**
Had a bit of trouble merging but should all be fine

### CODE REVIEW

**Comment by SoTBurst** [comment]
The swipe directions are wrong. And sometimes it doesn't register the swipe. Might feel better on a real device though.

**Comment by TheBlueBaronx** [comment]
Just checked, swipe directions are right - let's wait until @NightmindOfficial tested it

**Review by NightmindOfficial — CHANGES_REQUESTED** [review]
As indicated previously by @SoTBurst and me, this needs a rework first. Also talked about it in today's meeting.

**Comment by TheBlueBaronx** [comment]
Should work now (?) @NightmindOfficial. Testing stuff like this is a bitch on a simulator/emulator.

**Review by NightmindOfficial — APPROVED** [review]
The salmon löpps

**Pull request merged**
